version: "3"

env:
  ENVIRONMENT: "development"

  EVALUATOR_PORT: "3000"

  DATABASE_PORT: "54322"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"

includes:
  database:
    taskfile: ./database/Taskfile.yaml
    dir: ./database

  evaluator:
    taskfile: ./services/evaluator/Taskfile.yaml
    dir: ./services/evaluator

tasks:
  clean:
    desc: Clean root-managed local artifacts
    cmds:
      - task database:clean
      - task evaluator:clean

  lint:
    desc: Run lint checks across services
    cmds:
      - task evaluator:lint

  test:
    desc: Run tests across services
    cmds:
      - task evaluator:test
