version: "3"

vars:
  PORT: '{{default "3000" .PORT}}'

tasks:
  run-local:
    desc: Run the evaluator service locally
    dotenv:
      - .env
    cmds:
      - npm run dev

  clean:
    desc: Remove generated evaluator service artifacts
    cmds:
      - rm -rf build

  lint:
    desc: Run evaluator service lint checks
    cmds:
      - npm run format:check
      - npm run typecheck

  test:
    desc: Run the evaluator service test suite
    dotenv:
      - .env
    cmds:
      - npm test

  build:
    desc: Build the evaluator service Docker image
    cmds:
      - docker build --tag denki/evaluator:latest .

  run-docker:
    desc: Build and run the evaluator Docker container with local env
    dotenv:
      - .env
    deps:
      - build
    cmds:
      - docker run --rm --env-file .env --publish {{.PORT}}:{{.PORT}}
        denki/evaluator:latest
